CREATE DATABASE IF NOT EXISTS `seiheki_test` DEFAULT CHARSET UTF8MB4;

CREATE TABLE IF NOT EXISTS `records`(
	`id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(100) NOT NULL,
    `score` INT UNSIGNED NOT NULL,
    `ip` VARCHAR(20),
    `position` VARCHAR(200)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;