CREATE DATABASE IF NOT EXISTS `seiheki_test` DEFAULT CHARSET UTF8MB4records;

CREATE TABLE IF NOT EXISTS `records`(
	`id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(100) NOT NULL,
    `score` INT UNSIGNED NOT NULL,
    `ip` VARCHAR(20),
    `position` VARCHAR(200),
    `real` BOOLEAN NOT NULL DEFAULT 1 /* 是否可信，由用户定义 */
)ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;